export interface EmojiEntry {
  emoji: string;
  /** Lowercase English search terms */
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiEntry[];
}

const e = (emoji: string, ...keywords: string[]): EmojiEntry => ({
  emoji,
  keywords: keywords.map((k) => k.toLowerCase()),
});

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys',
    icon: '😀',
    emojis: [
      e('😀', 'grinning', 'smile', 'happy'),
      e('😃', 'smiley', 'happy', 'joy'),
      e('😄', 'smile', 'happy', 'joy'),
      e('😁', 'beaming', 'grin'),
      e('😆', 'laughing', 'lol'),
      e('😅', 'sweat', 'smile'),
      e('🤣', 'rofl', 'laugh'),
      e('😂', 'joy', 'tears', 'laugh'),
      e('🙂', 'slight', 'smile'),
      e('🙃', 'upside', 'down'),
      e('😉', 'wink'),
      e('😊', 'blush', 'smile'),
      e('😇', 'innocent', 'angel'),
      e('🥰', 'love', 'hearts'),
      e('😍', 'heart', 'eyes', 'love'),
      e('🤩', 'star', 'eyes'),
      e('😘', 'kiss', 'heart'),
      e('😗', 'kissing'),
      e('😚', 'kissing', 'closed'),
      e('😙', 'kissing', 'smile'),
      e('🥲', 'smile', 'tear'),
      e('😋', 'yum', 'tongue'),
      e('😛', 'tongue'),
      e('😜', 'wink', 'tongue'),
      e('🤪', 'zany'),
      e('😝', 'squint', 'tongue'),
      e('🤑', 'money', 'mouth'),
      e('🤗', 'hug', 'hugging'),
      e('🤭', 'hand', 'mouth'),
      e('🤫', 'shush', 'quiet'),
      e('🤔', 'thinking'),
      e('🫡', 'salute'),
      e('🤐', 'zipper', 'mouth'),
      e('🤨', 'raised', 'eyebrow'),
      e('😐', 'neutral'),
      e('😑', 'expressionless'),
      e('😶', 'no', 'mouth'),
      e('🫥', 'dotted', 'line'),
      e('😏', 'smirk'),
      e('😒', 'unamused'),
      e('🙄', 'roll', 'eyes'),
      e('😬', 'grimace'),
      e('🤥', 'lying', 'pinocchio'),
      e('😌', 'relieved'),
      e('😔', 'pensive', 'sad'),
      e('😪', 'sleepy'),
      e('🤤', 'drool'),
      e('😴', 'sleep', 'zzz'),
      e('😷', 'mask', 'sick'),
      e('🤒', 'thermometer', 'sick'),
      e('🤕', 'bandage', 'hurt'),
      e('🤢', 'nauseated', 'sick'),
      e('🤮', 'vomit', 'sick'),
      e('🤧', 'sneeze'),
      e('🥵', 'hot', 'sweat'),
      e('🥶', 'cold', 'freeze'),
      e('🥴', 'woozy'),
      e('😵', 'dizzy'),
      e('🤯', 'exploding', 'head'),
      e('🤠', 'cowboy'),
      e('🥳', 'party'),
      e('🥸', 'disguise'),
      e('😎', 'cool', 'sunglasses'),
      e('🤓', 'nerd', 'glasses'),
      e('🧐', 'monocle'),
      e('😕', 'confused'),
      e('🫤', 'diagonal', 'mouth'),
      e('😟', 'worried'),
      e('🙁', 'frown'),
      e('☹️', 'frown'),
      e('😮', 'open', 'mouth'),
      e('😯', 'hushed'),
      e('😲', 'astonished'),
      e('😳', 'flushed'),
      e('🥺', 'pleading', 'puppy'),
      e('🥹', 'holding', 'tears'),
      e('😦', 'frown', 'open'),
      e('😧', 'anguished'),
      e('😨', 'fearful', 'scared'),
      e('😰', 'anxious', 'sweat'),
      e('😥', 'sad', 'relieved'),
      e('😢', 'cry', 'tear'),
      e('😭', 'sob', 'cry'),
      e('😱', 'scream', 'fear'),
      e('😖', 'confounded'),
      e('😣', 'persevere'),
      e('😞', 'disappointed'),
      e('😓', 'downcast', 'sweat'),
      e('😩', 'weary', 'tired'),
      e('😫', 'tired'),
      e('🥱', 'yawn'),
      e('😤', 'steam', 'nose'),
      e('😡', 'angry', 'mad'),
      e('😠', 'angry'),
      e('🤬', 'swearing', 'cursing'),
      e('😈', 'smiling', 'devil'),
      e('👿', 'angry', 'devil'),
      e('💀', 'skull', 'dead'),
      e('☠️', 'skull', 'crossbones'),
      e('💩', 'poop', 'poo'),
      e('🤡', 'clown'),
      e('👹', 'ogre'),
      e('👺', 'goblin'),
      e('👻', 'ghost'),
      e('👽', 'alien'),
      e('🤖', 'robot'),
    ],
  },
  {
    id: 'people',
    label: 'People',
    icon: '👋',
    emojis: [
      e('👋', 'wave', 'hello', 'hi'),
      e('🤚', 'raised', 'back', 'hand'),
      e('🖐️', 'hand', 'fingers'),
      e('✋', 'raised', 'hand', 'stop'),
      e('🖖', 'vulcan', 'spock'),
      e('🫱', 'right', 'hand'),
      e('🫲', 'left', 'hand'),
      e('👌', 'ok'),
      e('🤌', 'pinched', 'fingers'),
      e('🤏', 'pinch'),
      e('✌️', 'victory', 'peace'),
      e('🤞', 'crossed', 'fingers', 'luck'),
      e('🫰', 'heart', 'hands'),
      e('🤟', 'love', 'you'),
      e('🤘', 'rock', 'horns'),
      e('🤙', 'call', 'me'),
      e('👈', 'point', 'left'),
      e('👉', 'point', 'right'),
      e('👆', 'point', 'up'),
      e('👇', 'point', 'down'),
      e('☝️', 'index', 'up'),
      e('👍', 'thumbs', 'up', 'like'),
      e('👎', 'thumbs', 'down', 'dislike'),
      e('✊', 'fist'),
      e('👊', 'punch', 'fist'),
      e('🤛', 'left', 'fist'),
      e('🤜', 'right', 'fist'),
      e('👏', 'clap', 'applause'),
      e('🙌', 'raising', 'hands', 'celebrate'),
      e('🫶', 'heart', 'hands'),
      e('👐', 'open', 'hands'),
      e('🤲', 'palms', 'up'),
      e('🤝', 'handshake'),
      e('🙏', 'pray', 'thanks'),
      e('💪', 'muscle', 'strong'),
      e('🦾', 'mechanical', 'arm'),
      e('🦿', 'mechanical', 'leg'),
      e('🦵', 'leg'),
      e('🦶', 'foot'),
      e('👂', 'ear'),
      e('👃', 'nose'),
      e('🧠', 'brain'),
      e('🫀', 'heart', 'organ'),
      e('🫁', 'lungs'),
      e('🦷', 'tooth'),
      e('🦴', 'bone'),
      e('👀', 'eyes'),
      e('👁️', 'eye'),
      e('👅', 'tongue'),
      e('👄', 'lips', 'mouth'),
      e('👶', 'baby'),
      e('🧒', 'child'),
      e('👦', 'boy'),
      e('👧', 'girl'),
      e('🧑', 'person'),
      e('👱', 'blond'),
      e('👨', 'man'),
      e('👩', 'woman'),
      e('🧓', 'older', 'adult'),
      e('👴', 'old', 'man'),
      e('👵', 'old', 'woman'),
      e('🙍', 'frown', 'person'),
      e('🙎', 'pout'),
      e('🙅', 'no', 'gesture'),
      e('🙆', 'ok', 'gesture'),
      e('💁', 'information', 'desk'),
      e('🙋', 'raising', 'hand'),
      e('🧏', 'deaf'),
      e('🙇', 'bow'),
      e('🤦', 'facepalm'),
      e('🤷', 'shrug'),
      e('👮', 'police'),
      e('🕵️', 'detective'),
      e('💂', 'guard'),
      e('🥷', 'ninja'),
      e('👷', 'construction'),
      e('🤴', 'prince'),
      e('👸', 'princess'),
      e('👳', 'turban'),
      e('👲', 'skullcap'),
      e('🧕', 'hijab'),
      e('🤵', 'tuxedo'),
      e('👰', 'bride'),
      e('🤰', 'pregnant'),
      e('🤱', 'breast', 'feeding'),
      e('👼', 'angel', 'baby'),
      e('🎅', 'santa'),
      e('🤶', 'mrs', 'claus'),
      e('🦸', 'superhero'),
      e('🦹', 'supervillain'),
      e('🧙', 'mage', 'wizard'),
      e('🧚', 'fairy'),
      e('🧛', 'vampire'),
      e('🧜', 'merperson'),
      e('🧝', 'elf'),
      e('🧞', 'genie'),
      e('🧟', 'zombie'),
      e('💆', 'massage'),
      e('💇', 'haircut'),
      e('🚶', 'walk', 'walking'),
      e('🏃', 'run', 'running'),
      e('💃', 'dance'),
      e('🕺', 'dance', 'man'),
      e('🧍', 'standing'),
      e('🧎', 'kneeling'),
    ],
  },
  {
    id: 'animals',
    label: 'Animals',
    icon: '🐶',
    emojis: [
      e('🐶', 'dog', 'puppy'),
      e('🐱', 'cat', 'kitten'),
      e('🐭', 'mouse'),
      e('🐹', 'hamster'),
      e('🐰', 'rabbit', 'bunny'),
      e('🦊', 'fox'),
      e('🐻', 'bear'),
      e('🐼', 'panda'),
      e('🐻‍❄️', 'polar', 'bear'),
      e('🐨', 'koala'),
      e('🐯', 'tiger'),
      e('🦁', 'lion'),
      e('🐮', 'cow'),
      e('🐷', 'pig'),
      e('🐸', 'frog'),
      e('🐵', 'monkey'),
      e('🙈', 'see', 'no', 'evil'),
      e('🙉', 'hear', 'no', 'evil'),
      e('🙊', 'speak', 'no', 'evil'),
      e('🐒', 'monkey'),
      e('🐔', 'chicken'),
      e('🐧', 'penguin'),
      e('🐦', 'bird'),
      e('🐤', 'chick'),
      e('🦆', 'duck'),
      e('🦅', 'eagle'),
      e('🦉', 'owl'),
      e('🦇', 'bat'),
      e('🐺', 'wolf'),
      e('🐗', 'boar'),
      e('🐴', 'horse'),
      e('🦄', 'unicorn'),
      e('🐝', 'bee'),
      e('🪱', 'worm'),
      e('🐛', 'bug'),
      e('🦋', 'butterfly'),
      e('🐌', 'snail'),
      e('🐞', 'ladybug'),
      e('🐜', 'ant'),
      e('🪰', 'fly'),
      e('🪲', 'beetle'),
      e('🪳', 'cockroach'),
      e('🦟', 'mosquito'),
      e('🦗', 'cricket'),
      e('🕷️', 'spider'),
      e('🦂', 'scorpion'),
      e('🐢', 'turtle'),
      e('🐍', 'snake'),
      e('🦎', 'lizard'),
      e('🦖', 't-rex', 'dinosaur'),
      e('🦕', 'sauropod', 'dinosaur'),
      e('🐙', 'octopus'),
      e('🦑', 'squid'),
      e('🦐', 'shrimp'),
      e('🦞', 'lobster'),
      e('🦀', 'crab'),
      e('🐡', 'blowfish'),
      e('🐠', 'tropical', 'fish'),
      e('🐟', 'fish'),
      e('🐬', 'dolphin'),
      e('🐳', 'whale'),
      e('🐋', 'whale'),
      e('🦈', 'shark'),
      e('🐊', 'crocodile'),
      e('🐅', 'tiger'),
      e('🐆', 'leopard'),
      e('🦓', 'zebra'),
      e('🦍', 'gorilla'),
      e('🦧', 'orangutan'),
      e('🐘', 'elephant'),
      e('🦛', 'hippo'),
      e('🦏', 'rhino'),
      e('🐪', 'camel'),
      e('🐫', 'camel'),
      e('🦒', 'giraffe'),
      e('🦘', 'kangaroo'),
      e('🐃', 'buffalo'),
      e('🐂', 'ox'),
      e('🐄', 'cow'),
      e('🐎', 'horse'),
      e('🐖', 'pig'),
      e('🐏', 'ram'),
      e('🐑', 'sheep'),
      e('🦙', 'llama'),
      e('🐐', 'goat'),
      e('🦌', 'deer'),
      e('🐕', 'dog'),
      e('🐩', 'poodle'),
      e('🦮', 'guide', 'dog'),
      e('🐈', 'cat'),
      e('🐓', 'rooster'),
      e('🦃', 'turkey'),
      e('🦚', 'peacock'),
      e('🦜', 'parrot'),
      e('🦢', 'swan'),
      e('🕊️', 'dove', 'peace'),
    ],
  },
  {
    id: 'food',
    label: 'Food',
    icon: '🍎',
    emojis: [
      e('🍎', 'apple', 'red'),
      e('🍏', 'apple', 'green'),
      e('🍐', 'pear'),
      e('🍊', 'orange', 'tangerine'),
      e('🍋', 'lemon'),
      e('🍌', 'banana'),
      e('🍉', 'watermelon'),
      e('🍇', 'grapes'),
      e('🍓', 'strawberry'),
      e('🫐', 'blueberry'),
      e('🍈', 'melon'),
      e('🍒', 'cherry'),
      e('🍑', 'peach'),
      e('🥭', 'mango'),
      e('🍍', 'pineapple'),
      e('🥥', 'coconut'),
      e('🥝', 'kiwi'),
      e('🍅', 'tomato'),
      e('🍆', 'eggplant'),
      e('🥑', 'avocado'),
      e('🥦', 'broccoli'),
      e('🥬', 'leafy', 'green'),
      e('🥒', 'cucumber'),
      e('🌶️', 'pepper', 'hot'),
      e('🫑', 'bell', 'pepper'),
      e('🌽', 'corn'),
      e('🥕', 'carrot'),
      e('🫒', 'olive'),
      e('🧄', 'garlic'),
      e('🧅', 'onion'),
      e('🥔', 'potato'),
      e('🍠', 'sweet', 'potato'),
      e('🥐', 'croissant'),
      e('🥯', 'bagel'),
      e('🍞', 'bread'),
      e('🥖', 'baguette'),
      e('🥨', 'pretzel'),
      e('🧀', 'cheese'),
      e('🥚', 'egg'),
      e('🍳', 'cooking', 'egg'),
      e('🧈', 'butter'),
      e('🥞', 'pancakes'),
      e('🧇', 'waffle'),
      e('🥓', 'bacon'),
      e('🥩', 'steak', 'meat'),
      e('🍗', 'poultry', 'leg'),
      e('🍖', 'meat', 'bone'),
      e('🌭', 'hotdog'),
      e('🍔', 'burger', 'hamburger'),
      e('🍟', 'fries'),
      e('🍕', 'pizza'),
      e('🫓', 'flatbread'),
      e('🥪', 'sandwich'),
      e('🥙', 'stuffed', 'flatbread'),
      e('🧆', 'falafel'),
      e('🌮', 'taco'),
      e('🌯', 'burrito'),
      e('🫔', 'tamale'),
      e('🥗', 'salad'),
      e('🥘', 'paella'),
      e('🫕', 'fondue'),
      e('🍝', 'spaghetti', 'pasta'),
      e('🍜', 'ramen', 'noodles'),
      e('🍲', 'pot', 'food'),
      e('🍛', 'curry'),
      e('🍣', 'sushi'),
      e('🍱', 'bento'),
      e('🥟', 'dumpling'),
      e('🦪', 'oyster'),
      e('🍤', 'fried', 'shrimp'),
      e('🍙', 'rice', 'ball'),
      e('🍚', 'rice'),
      e('🍘', 'rice', 'cracker'),
      e('🍥', 'fish', 'cake'),
      e('🥠', 'fortune', 'cookie'),
      e('🥮', 'moon', 'cake'),
      e('🍢', 'oden'),
      e('🍡', 'dango'),
      e('🍧', 'shaved', 'ice'),
      e('🍨', 'ice', 'cream'),
      e('🍦', 'soft', 'ice', 'cream'),
      e('🥧', 'pie'),
      e('🧁', 'cupcake'),
      e('🍰', 'cake', 'shortcake'),
      e('🎂', 'birthday', 'cake'),
      e('🍮', 'custard'),
      e('🍭', 'lollipop', 'candy'),
      e('🍬', 'candy'),
      e('🍫', 'chocolate'),
      e('🍿', 'popcorn'),
      e('🍩', 'donut'),
      e('🍪', 'cookie'),
      e('🌰', 'chestnut'),
      e('🥜', 'peanuts'),
      e('☕', 'coffee'),
      e('🫖', 'teapot', 'tea'),
      e('🍵', 'tea'),
      e('🧃', 'juice'),
      e('🥤', 'cup', 'straw'),
      e('🧋', 'bubble', 'tea'),
      e('🍶', 'sake'),
      e('🍺', 'beer'),
      e('🍻', 'beers', 'cheers'),
      e('🥂', 'champagne', 'cheers'),
      e('🍷', 'wine'),
      e('🥃', 'whiskey'),
      e('🍸', 'cocktail'),
      e('🍹', 'tropical', 'drink'),
      e('🧉', 'mate'),
      e('🍾', 'champagne', 'bottle'),
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    icon: '⚽',
    emojis: [
      e('⚽', 'soccer', 'football'),
      e('🏀', 'basketball'),
      e('🏈', 'football', 'american'),
      e('⚾', 'baseball'),
      e('🥎', 'softball'),
      e('🎾', 'tennis'),
      e('🏐', 'volleyball'),
      e('🏉', 'rugby'),
      e('🥏', 'frisbee'),
      e('🎱', 'pool', '8ball'),
      e('🪀', 'yo-yo'),
      e('🏓', 'ping', 'pong'),
      e('🏸', 'badminton'),
      e('🏒', 'hockey'),
      e('🥅', 'goal'),
      e('⛳', 'golf'),
      e('🪁', 'kite'),
      e('🏹', 'bow', 'arrow'),
      e('🎣', 'fishing'),
      e('🤿', 'diving'),
      e('🥊', 'boxing'),
      e('🥋', 'martial', 'arts'),
      e('🎽', 'running', 'shirt'),
      e('🛹', 'skateboard'),
      e('🛼', 'roller', 'skate'),
      e('🛷', 'sled'),
      e('⛸️', 'ice', 'skate'),
      e('🥌', 'curling'),
      e('🎿', 'ski'),
      e('⛷️', 'skier'),
      e('🏂', 'snowboard'),
      e('🪂', 'parachute'),
      e('🏋️', 'weight', 'lifting'),
      e('🤼', 'wrestling'),
      e('🤸', 'cartwheel'),
      e('⛹️', 'basketball', 'person'),
      e('🤺', 'fencing'),
      e('🤾', 'handball'),
      e('🏌️', 'golfing'),
      e('🏇', 'horse', 'racing'),
      e('🧘', 'yoga'),
      e('🏄', 'surfing'),
      e('🏊', 'swimming'),
      e('🤽', 'water', 'polo'),
      e('🚣', 'rowing'),
      e('🧗', 'climbing'),
      e('🚴', 'biking', 'cycling'),
      e('🚵', 'mountain', 'biking'),
      e('🎪', 'circus'),
      e('🎭', 'theater', 'drama'),
      e('🎨', 'art', 'palette'),
      e('🎬', 'clapper', 'movie'),
      e('🎤', 'microphone', 'karaoke'),
      e('🎧', 'headphones'),
      e('🎼', 'music', 'score'),
      e('🎹', 'piano'),
      e('🥁', 'drum'),
      e('🪘', 'long', 'drum'),
      e('🎷', 'saxophone'),
      e('🎺', 'trumpet'),
      e('🎸', 'guitar'),
      e('🪕', 'banjo'),
      e('🎻', 'violin'),
      e('🎲', 'dice', 'game'),
      e('♟️', 'chess'),
      e('🎯', 'target', 'dart'),
      e('🎳', 'bowling'),
      e('🎮', 'video', 'game'),
      e('🎰', 'slot', 'machine'),
      e('🧩', 'puzzle'),
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    icon: '🚗',
    emojis: [
      e('🚗', 'car'),
      e('🚕', 'taxi'),
      e('🚙', 'suv'),
      e('🚌', 'bus'),
      e('🚎', 'trolleybus'),
      e('🏎️', 'race', 'car'),
      e('🚓', 'police', 'car'),
      e('🚑', 'ambulance'),
      e('🚒', 'fire', 'engine'),
      e('🚐', 'minibus'),
      e('🛻', 'pickup'),
      e('🚚', 'truck'),
      e('🚛', 'lorry'),
      e('🚜', 'tractor'),
      e('🏍️', 'motorcycle'),
      e('🛵', 'scooter'),
      e('🚲', 'bicycle', 'bike'),
      e('🛴', 'kick', 'scooter'),
      e('🚂', 'train', 'locomotive'),
      e('🚆', 'train'),
      e('🚇', 'metro', 'subway'),
      e('🚊', 'tram'),
      e('🚉', 'station'),
      e('✈️', 'airplane', 'plane'),
      e('🛫', 'departure'),
      e('🛬', 'arrival'),
      e('🚀', 'rocket'),
      e('🛸', 'ufo', 'flying', 'saucer'),
      e('🚁', 'helicopter'),
      e('🛶', 'canoe'),
      e('⛵', 'sailboat'),
      e('🚤', 'speedboat'),
      e('🛥️', 'motor', 'boat'),
      e('🚢', 'ship'),
      e('⚓', 'anchor'),
      e('🗼', 'tower', 'tokyo'),
      e('🏰', 'castle'),
      e('🏯', 'castle', 'japanese'),
      e('🏟️', 'stadium'),
      e('🎡', 'ferris', 'wheel'),
      e('🎢', 'roller', 'coaster'),
      e('🎠', 'carousel'),
      e('⛲', 'fountain'),
      e('⛱️', 'umbrella', 'beach'),
      e('🏖️', 'beach'),
      e('🏝️', 'island'),
      e('🏜️', 'desert'),
      e('🌋', 'volcano'),
      e('⛰️', 'mountain'),
      e('🏔️', 'snow', 'mountain'),
      e('🗻', 'mount', 'fuji'),
      e('🏕️', 'camping'),
      e('⛺', 'tent'),
      e('🏠', 'house', 'home'),
      e('🏡', 'house', 'garden'),
      e('🏢', 'office'),
      e('🏣', 'post', 'office'),
      e('🏥', 'hospital'),
      e('🏦', 'bank'),
      e('🏨', 'hotel'),
      e('🏩', 'love', 'hotel'),
      e('🏪', 'convenience', 'store'),
      e('🏫', 'school'),
      e('🏬', 'department', 'store'),
      e('🏭', 'factory'),
      e('🗽', 'statue', 'liberty'),
      e('🗿', 'moai'),
      e('🌁', 'foggy'),
      e('🌃', 'night'),
      e('🌄', 'sunrise', 'mountains'),
      e('🌅', 'sunrise'),
      e('🌆', 'cityscape', 'dusk'),
      e('🌇', 'sunset'),
      e('🌉', 'bridge', 'night'),
      e('🌌', 'milky', 'way'),
      e('🎆', 'fireworks'),
      e('🎇', 'sparkler'),
      e('🌠', 'shooting', 'star'),
      e('🌈', 'rainbow'),
      e('🌞', 'sun'),
      e('🌝', 'moon', 'face'),
      e('🌙', 'crescent', 'moon'),
      e('⭐', 'star'),
      e('🌟', 'glowing', 'star'),
      e('✨', 'sparkles'),
      e('⚡', 'lightning', 'zap'),
      e('🔥', 'fire'),
      e('💧', 'droplet', 'water'),
      e('🌊', 'wave', 'ocean'),
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      e('⌚', 'watch'),
      e('📱', 'phone', 'mobile'),
      e('💻', 'laptop', 'computer'),
      e('⌨️', 'keyboard'),
      e('🖥️', 'desktop'),
      e('🖨️', 'printer'),
      e('🖱️', 'mouse', 'computer'),
      e('💽', 'minidisc'),
      e('💾', 'floppy', 'disk'),
      e('💿', 'cd', 'optical'),
      e('📀', 'dvd'),
      e('📷', 'camera'),
      e('📸', 'camera', 'flash'),
      e('📹', 'video', 'camera'),
      e('🎥', 'movie', 'camera'),
      e('📞', 'telephone'),
      e('☎️', 'phone'),
      e('📺', 'television', 'tv'),
      e('📻', 'radio'),
      e('🎙️', 'microphone', 'studio'),
      e('⏰', 'alarm', 'clock'),
      e('⌛', 'hourglass'),
      e('⏳', 'hourglass', 'done'),
      e('📡', 'satellite'),
      e('🔋', 'battery'),
      e('🔌', 'electric', 'plug'),
      e('💡', 'light', 'bulb', 'idea'),
      e('🔦', 'flashlight'),
      e('🕯️', 'candle'),
      e('🧯', 'fire', 'extinguisher'),
      e('🛢️', 'oil'),
      e('💸', 'money', 'wings'),
      e('💵', 'dollar'),
      e('💴', 'yen'),
      e('💶', 'euro'),
      e('💷', 'pound'),
      e('💰', 'money', 'bag'),
      e('💳', 'credit', 'card'),
      e('💎', 'gem', 'diamond'),
      e('⚖️', 'balance', 'scale'),
      e('🔧', 'wrench', 'tool'),
      e('🔨', 'hammer'),
      e('⚒️', 'hammer', 'pick'),
      e('🛠️', 'tools'),
      e('⛏️', 'pick'),
      e('🔩', 'nut', 'bolt'),
      e('⚙️', 'gear'),
      e('🔗', 'link'),
      e('⛓️', 'chains'),
      e('🔫', 'gun', 'water'),
      e('💣', 'bomb'),
      e('🔪', 'knife'),
      e('🗡️', 'dagger'),
      e('🛡️', 'shield'),
      e('🚬', 'cigarette'),
      e('⚰️', 'coffin'),
      e('🪦', 'headstone'),
      e('⚱️', 'urn'),
      e('🏺', 'amphora'),
      e('🔮', 'crystal', 'ball'),
      e('📿', 'prayer', 'beads'),
      e('🧿', 'nazar', 'evil', 'eye'),
      e('💈', 'barber', 'pole'),
      e('⚗️', 'alembic'),
      e('🔭', 'telescope'),
      e('🔬', 'microscope'),
      e('🩹', 'bandage'),
      e('🩺', 'stethoscope'),
      e('💊', 'pill'),
      e('💉', 'syringe'),
      e('🩸', 'blood'),
      e('🧬', 'dna'),
      e('🦠', 'microbe'),
      e('🧫', 'petri', 'dish'),
      e('🧪', 'test', 'tube'),
      e('🌡️', 'thermometer'),
      e('🧹', 'broom'),
      e('🧺', 'basket'),
      e('🧻', 'toilet', 'paper'),
      e('🚽', 'toilet'),
      e('🚿', 'shower'),
      e('🛁', 'bathtub'),
      e('🧼', 'soap'),
      e('🪥', 'toothbrush'),
      e('🪒', 'razor'),
      e('🧽', 'sponge'),
      e('🧴', 'lotion'),
      e('🛎️', 'bellhop'),
      e('🔑', 'key'),
      e('🗝️', 'old', 'key'),
      e('🚪', 'door'),
      e('🪑', 'chair'),
      e('🛋️', 'couch'),
      e('🛏️', 'bed'),
      e('🧸', 'teddy', 'bear'),
      e('🖼️', 'frame', 'picture'),
      e('🛍️', 'shopping', 'bags'),
      e('🎁', 'gift', 'present'),
      e('🎈', 'balloon'),
      e('🎏', 'carp', 'streamer'),
      e('🎀', 'ribbon'),
      e('🎊', 'confetti', 'ball'),
      e('🎉', 'party', 'popper', 'tada'),
      e('🎎', 'dolls'),
      e('🏮', 'lantern'),
      e('🎐', 'wind', 'chime'),
      e('🧧', 'red', 'envelope'),
      e('✉️', 'envelope', 'email'),
      e('📩', 'envelope', 'arrow'),
      e('📨', 'incoming', 'envelope'),
      e('📧', 'email'),
      e('💌', 'love', 'letter'),
      e('📥', 'inbox'),
      e('📤', 'outbox'),
      e('📦', 'package'),
      e('🏷️', 'label', 'tag'),
      e('📪', 'mailbox'),
      e('📫', 'mailbox', 'flag'),
      e('📬', 'mailbox', 'open'),
      e('📭', 'mailbox', 'no', 'mail'),
      e('📮', 'postbox'),
      e('📝', 'memo', 'note'),
      e('📄', 'page'),
      e('📃', 'page', 'curl'),
      e('📑', 'bookmark', 'tabs'),
      e('🧾', 'receipt'),
      e('📊', 'chart', 'bar'),
      e('📈', 'chart', 'increasing'),
      e('📉', 'chart', 'decreasing'),
      e('📋', 'clipboard'),
      e('📌', 'pushpin'),
      e('📍', 'pin', 'location'),
      e('📎', 'paperclip'),
      e('🖇️', 'paperclips'),
      e('📏', 'ruler'),
      e('📐', 'triangle', 'ruler'),
      e('✂️', 'scissors'),
      e('🗃️', 'card', 'file'),
      e('🗄️', 'file', 'cabinet'),
      e('🗑️', 'trash', 'wastebasket'),
      e('🔒', 'lock'),
      e('🔓', 'unlock'),
      e('🔏', 'lock', 'pen'),
      e('🔐', 'lock', 'key'),
      e('🔑', 'key'),
      e('🗝️', 'old', 'key'),
      e('🔨', 'hammer'),
      e('⛏️', 'pick'),
      e('⚒️', 'hammer', 'pick'),
      e('🛠️', 'tools'),
      e('🗡️', 'dagger'),
      e('⚔️', 'crossed', 'swords'),
      e('🔫', 'pistol'),
      e('🏹', 'bow'),
      e('🛡️', 'shield'),
      e('🔧', 'wrench'),
      e('🔩', 'nut', 'bolt'),
      e('⚙️', 'gear'),
      e('🗜️', 'clamp'),
      e('⚖️', 'scale'),
      e('🦯', 'probing', 'cane'),
      e('🔗', 'link'),
      e('⛓️', 'chain'),
      e('🪝', 'hook'),
      e('🧰', 'toolbox'),
      e('🧲', 'magnet'),
      e('🪜', 'ladder'),
      e('⚗️', 'alembic'),
      e('🧪', 'test', 'tube'),
      e('🧫', 'petri', 'dish'),
      e('🧬', 'dna'),
      e('🔬', 'microscope'),
      e('🔭', 'telescope'),
      e('📡', 'satellite'),
      e('💉', 'syringe'),
      e('🩸', 'drop', 'blood'),
      e('💊', 'pill'),
      e('🩹', 'adhesive', 'bandage'),
      e('🩺', 'stethoscope'),
      e('🚪', 'door'),
      e('🛗', 'elevator'),
      e('🪞', 'mirror'),
      e('🪟', 'window'),
      e('🛏️', 'bed'),
      e('🛋️', 'couch'),
      e('🪑', 'chair'),
      e('🚽', 'toilet'),
      e('🪠', 'plunger'),
      e('🚿', 'shower'),
      e('🛁', 'bathtub'),
      e('🪤', 'mouse', 'trap'),
      e('🪒', 'razor'),
      e('🧴', 'lotion', 'bottle'),
      e('🧷', 'safety', 'pin'),
      e('🧹', 'broom'),
      e('🧺', 'basket'),
      e('🧻', 'roll', 'paper'),
      e('🪣', 'bucket'),
      e('🧼', 'soap'),
      e('🫧', 'bubbles'),
      e('🪥', 'toothbrush'),
      e('🧽', 'sponge'),
      e('🧯', 'fire', 'extinguisher'),
      e('🛒', 'shopping', 'cart'),
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '❤️',
    emojis: [
      e('❤️', 'heart', 'red', 'love'),
      e('🧡', 'orange', 'heart'),
      e('💛', 'yellow', 'heart'),
      e('💚', 'green', 'heart'),
      e('💙', 'blue', 'heart'),
      e('💜', 'purple', 'heart'),
      e('🖤', 'black', 'heart'),
      e('🤍', 'white', 'heart'),
      e('🤎', 'brown', 'heart'),
      e('💔', 'broken', 'heart'),
      e('❣️', 'heart', 'exclamation'),
      e('💕', 'two', 'hearts'),
      e('💞', 'revolving', 'hearts'),
      e('💓', 'beating', 'heart'),
      e('💗', 'growing', 'heart'),
      e('💖', 'sparkling', 'heart'),
      e('💘', 'heart', 'arrow', 'cupid'),
      e('💝', 'heart', 'ribbon'),
      e('💟', 'heart', 'decoration'),
      e('☮️', 'peace'),
      e('✝️', 'cross', 'latin'),
      e('☪️', 'star', 'crescent'),
      e('🕉️', 'om'),
      e('☸️', 'wheel', 'dharma'),
      e('✡️', 'star', 'david'),
      e('🔯', 'dotted', 'six', 'pointed'),
      e('🕎', 'menorah'),
      e('☯️', 'yin', 'yang'),
      e('☦️', 'orthodox', 'cross'),
      e('🛐', 'place', 'worship'),
      e('⛎', 'ophiuchus'),
      e('♈', 'aries'),
      e('♉', 'taurus'),
      e('♊', 'gemini'),
      e('♋', 'cancer'),
      e('♌', 'leo'),
      e('♍', 'virgo'),
      e('♎', 'libra'),
      e('♏', 'scorpio'),
      e('♐', 'sagittarius'),
      e('♑', 'capricorn'),
      e('♒', 'aquarius'),
      e('♓', 'pisces'),
      e('🔀', 'shuffle'),
      e('🔁', 'repeat'),
      e('🔂', 'repeat', 'one'),
      e('▶️', 'play'),
      e('⏩', 'fast', 'forward'),
      e('⏭️', 'next'),
      e('⏯️', 'play', 'pause'),
      e('◀️', 'reverse'),
      e('⏪', 'rewind'),
      e('⏮️', 'previous'),
      e('🔼', 'up'),
      e('⏫', 'fast', 'up'),
      e('🔽', 'down'),
      e('⏬', 'fast', 'down'),
      e('⏸️', 'pause'),
      e('⏹️', 'stop'),
      e('⏺️', 'record'),
      e('⏏️', 'eject'),
      e('🎦', 'cinema'),
      e('🔅', 'dim'),
      e('🔆', 'bright'),
      e('📶', 'signal'),
      e('📳', 'vibration'),
      e('📴', 'mobile', 'off'),
      e('♀️', 'female'),
      e('♂️', 'male'),
      e('⚧️', 'transgender'),
      e('✖️', 'multiply', 'x'),
      e('➕', 'plus'),
      e('➖', 'minus'),
      e('➗', 'divide'),
      e('♾️', 'infinity'),
      e('‼️', 'double', 'exclamation'),
      e('⁉️', 'exclamation', 'question'),
      e('❓', 'question'),
      e('❔', 'white', 'question'),
      e('❕', 'white', 'exclamation'),
      e('❗', 'exclamation'),
      e('〰️', 'wavy', 'dash'),
      e('💱', 'currency', 'exchange'),
      e('💲', 'heavy', 'dollar'),
      e('⚕️', 'medical'),
      e('♻️', 'recycle'),
      e('⚜️', 'fleur', 'de', 'lis'),
      e('🔱', 'trident'),
      e('📛', 'name', 'badge'),
      e('🔰', 'beginner'),
      e('⭕', 'hollow', 'red', 'circle'),
      e('✅', 'check', 'mark', 'button'),
      e('☑️', 'check', 'box'),
      e('✔️', 'check', 'mark'),
      e('❌', 'cross', 'mark', 'x'),
      e('❎', 'cross', 'mark', 'button'),
      e('➰', 'curly', 'loop'),
      e('➿', 'double', 'curly', 'loop'),
      e('〽️', 'part', 'alternation'),
      e('✳️', 'eight', 'spoked'),
      e('✴️', 'eight', 'pointed'),
      e('❇️', 'sparkle'),
      e('©️', 'copyright'),
      e('®️', 'registered'),
      e('™️', 'trademark'),
      e('#️⃣', 'hash', 'number'),
      e('*️⃣', 'asterisk'),
      e('0️⃣', 'zero'),
      e('1️⃣', 'one'),
      e('2️⃣', 'two'),
      e('3️⃣', 'three'),
      e('4️⃣', 'four'),
      e('5️⃣', 'five'),
      e('6️⃣', 'six'),
      e('7️⃣', 'seven'),
      e('8️⃣', 'eight'),
      e('9️⃣', 'nine'),
      e('🔟', 'ten'),
      e('🔠', 'abcd', 'uppercase'),
      e('🔡', 'abcd', 'lowercase'),
      e('🔢', 'numbers'),
      e('🔣', 'symbols'),
      e('🔤', 'abc'),
      e('🅰️', 'a', 'blood'),
      e('🅱️', 'b', 'blood'),
      e('🆎', 'ab', 'blood'),
      e('🆑', 'cl'),
      e('🆒', 'cool'),
      e('🆓', 'free'),
      e('ℹ️', 'information'),
      e('🆔', 'id'),
      e('Ⓜ️', 'm', 'circle'),
      e('🆕', 'new'),
      e('🆖', 'ng'),
      e('🅾️', 'o', 'blood'),
      e('🆗', 'ok'),
      e('🅿️', 'parking'),
      e('🆘', 'sos'),
      e('🆙', 'up'),
      e('🆚', 'vs'),
      e('🈁', 'japanese', 'here'),
      e('🈂️', 'japanese', 'service'),
      e('🈷️', 'japanese', 'monthly'),
      e('🈶', 'japanese', 'not', 'free'),
      e('🈯', 'japanese', 'reserved'),
      e('🉐', 'japanese', 'bargain'),
      e('🈹', 'japanese', 'discount'),
      e('🈚', 'japanese', 'free'),
      e('🈲', 'japanese', 'prohibited'),
      e('🉑', 'japanese', 'acceptable'),
      e('🈸', 'japanese', 'application'),
      e('🈴', 'japanese', 'passing'),
      e('🈳', 'japanese', 'vacancy'),
      e('㊗️', 'japanese', 'congratulations'),
      e('㊙️', 'japanese', 'secret'),
      e('🈺', 'japanese', 'open'),
      e('🈵', 'japanese', 'no', 'vacancy'),
      e('🔴', 'red', 'circle'),
      e('🟠', 'orange', 'circle'),
      e('🟡', 'yellow', 'circle'),
      e('🟢', 'green', 'circle'),
      e('🔵', 'blue', 'circle'),
      e('🟣', 'purple', 'circle'),
      e('🟤', 'brown', 'circle'),
      e('⚫', 'black', 'circle'),
      e('⚪', 'white', 'circle'),
      e('🟥', 'red', 'square'),
      e('🟧', 'orange', 'square'),
      e('🟨', 'yellow', 'square'),
      e('🟩', 'green', 'square'),
      e('🟦', 'blue', 'square'),
      e('🟪', 'purple', 'square'),
      e('🟫', 'brown', 'square'),
      e('⬛', 'black', 'large', 'square'),
      e('⬜', 'white', 'large', 'square'),
      e('◼️', 'black', 'medium', 'square'),
      e('◻️', 'white', 'medium', 'square'),
      e('◾', 'black', 'medium', 'small', 'square'),
      e('◽', 'white', 'medium', 'small', 'square'),
      e('▪️', 'black', 'small', 'square'),
      e('▫️', 'white', 'small', 'square'),
      e('🔶', 'large', 'orange', 'diamond'),
      e('🔷', 'large', 'blue', 'diamond'),
      e('🔸', 'small', 'orange', 'diamond'),
      e('🔹', 'small', 'blue', 'diamond'),
      e('🔺', 'red', 'triangle', 'up'),
      e('🔻', 'red', 'triangle', 'down'),
      e('💠', 'diamond', 'dot'),
      e('🔘', 'radio', 'button'),
      e('🔳', 'white', 'square', 'button'),
      e('🔲', 'black', 'square', 'button'),
    ],
  },
  {
    id: 'flags',
    label: 'Flags',
    icon: '🏳️',
    emojis: [
      e('🏳️', 'white', 'flag'),
      e('🏴', 'black', 'flag'),
      e('🏁', 'chequered', 'flag', 'race'),
      e('🚩', 'triangular', 'flag'),
      e('🏳️‍🌈', 'rainbow', 'flag', 'pride'),
      e('🏳️‍⚧️', 'transgender', 'flag'),
      e('🇺🇸', 'usa', 'america', 'united', 'states'),
      e('🇬🇧', 'uk', 'britain', 'united', 'kingdom'),
      e('🇨🇦', 'canada'),
      e('🇦🇺', 'australia'),
      e('🇩🇪', 'germany'),
      e('🇫🇷', 'france'),
      e('🇮🇹', 'italy'),
      e('🇪🇸', 'spain'),
      e('🇳🇱', 'netherlands'),
      e('🇧🇪', 'belgium'),
      e('🇨🇭', 'switzerland'),
      e('🇦🇹', 'austria'),
      e('🇸🇪', 'sweden'),
      e('🇳🇴', 'norway'),
      e('🇩🇰', 'denmark'),
      e('🇫🇮', 'finland'),
      e('🇵🇱', 'poland'),
      e('🇷🇺', 'russia'),
      e('🇺🇦', 'ukraine'),
      e('🇹🇷', 'turkey'),
      e('🇬🇷', 'greece'),
      e('🇵🇹', 'portugal'),
      e('🇮🇪', 'ireland'),
      e('🇮🇳', 'india'),
      e('🇨🇳', 'china'),
      e('🇯🇵', 'japan'),
      e('🇰🇷', 'south', 'korea', 'korea'),
      e('🇹🇼', 'taiwan'),
      e('🇭🇰', 'hong', 'kong'),
      e('🇸🇬', 'singapore'),
      e('🇲🇾', 'malaysia'),
      e('🇹🇭', 'thailand'),
      e('🇻🇳', 'vietnam'),
      e('🇮🇩', 'indonesia'),
      e('🇵🇭', 'philippines'),
      e('🇦🇪', 'uae', 'emirates'),
      e('🇸🇦', 'saudi', 'arabia'),
      e('🇮🇷', 'iran', 'persia', 'iranian'),
      e('🇮🇶', 'iraq'),
      e('🇪🇬', 'egypt'),
      e('🇿🇦', 'south', 'africa'),
      e('🇳🇬', 'nigeria'),
      e('🇰🇪', 'kenya'),
      e('🇧🇷', 'brazil'),
      e('🇦🇷', 'argentina'),
      e('🇲🇽', 'mexico'),
      e('🇨🇴', 'colombia'),
      e('🇨🇱', 'chile'),
      e('🇵🇪', 'peru'),
      e('🇳🇿', 'new', 'zealand'),
      e('🇵🇰', 'pakistan'),
      e('🇧🇩', 'bangladesh'),
      e('🇱🇰', 'sri', 'lanka'),
      e('🇦🇫', 'afghanistan'),
      e('🇶🇦', 'qatar'),
      e('🇰🇼', 'kuwait'),
      e('🇴🇲', 'oman'),
      e('🇧🇭', 'bahrain'),
      e('🇯🇴', 'jordan'),
      e('🇱🇧', 'lebanon'),
      e('🇸🇾', 'syria'),
      e('🇮🇱', 'israel'),
      e('🇵🇸', 'palestine'),
    ],
  },
];

/** Flat list used for search across all categories */
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis);

export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  return ALL_EMOJIS.filter((entry) => {
    if (entry.emoji.includes(q)) return true;
    return entry.keywords.some((kw) => kw.includes(q) || q.includes(kw));
  });
}
